#!/usr/bin/env bash

admin="$(id -nu 1000)"

USER_HOME=/home/$admin

CONFIGS=(
  "$USER_HOME/.config/fastfetch/config.jsonc"
  "$USER_HOME/.config/kitty/kitty.conf"
  "/etc/locale.conf"
  "/etc/dracut.conf.d/myflags.conf"
  "$USER_HOME/.config/ohmyposh/myprofile.yaml"
  "$USER_HOME/.zshrc"
  "$USER_HOME/.config/ghostty/config"
  "$USER_HOME/.zen/tizo6sbm.Default (release)/chrome/userChrome.css"
  "$USER_HOME/.zen/tizo6sbm.Default (release)/chrome/userContent.css"
  "$USER_HOME/.zen/tizo6sbm.Default (release)/chrome/natsumi-config.css"
  "$USER_HOME/.config/wofi/config"
  "$USER_HOME/.config/wofi/style.css"
  "$USER_HOME/.config/yazi/init.lua"
  "$USER_HOME/.config/yazi/keymap.toml"
  "$USER_HOME/.config/yazi/theme.toml"
  "$USER_HOME/.config/yazi/yazi.toml"
)

DEST_FOLDER="$USER_HOME/Dev/Linux/Config/$(hostname)"

mkdir -p "$DEST_FOLDER"
chown "$admin":"$admin" "$DEST_FOLDER"

# Backing up configs

for config in "${CONFIGS[@]}"; do
  if ! [[ -f $config ]]; then
    continue
  fi

  FILE_NAME=$(basename "$config")
  if [[ $(dirname "$config") == "$USER_HOME" ]]; then
    FILE_DIR="user"
  else
    FILE_DIR=$(basename "$(dirname "$config")")
  fi

  # This check is to make dot files (hidden files) visible
  if [[ $FILE_NAME == .* ]]; then
    FILE_NAME="${FILE_NAME#?}"
  fi

  # This check is to make dot folders (hidden folders) visible
  if [[ $FILE_DIR == .* ]]; then
    FILE_DIR="${FILE_DIR#?}"
  fi

  mkdir -p "$DEST_FOLDER"/"$FILE_DIR"
  chown "$admin":"$admin" "$DEST_FOLDER"/"$FILE_DIR"
  cp "$config" "$DEST_FOLDER"/"$FILE_DIR"/"$FILE_NAME"
done
