#!/usr/bin/env bash
# The intention is to make this into a cronjob or systemd timer to run periodically
# This script is a short-term solution

RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

if [ $EUID = 0 ]; then
  USER_HOME=$(getent passwd "$SUDO_USER" | cut -d: -f6)
else
  USER_HOME=$HOME
  echo -e "\n${RED}Some configs may require root permission to backup!${NC}\n"
fi

CONFIGS=(
  "$USER_HOME/.config/fastfetch/config.jsonc"
  "$USER_HOME/.config/kitty/kitty.conf"
  "/etc/locale.conf"
  "/etc/dracut.conf.d/myflags.conf"
  "$USER_HOME/.config/ohmyposh/myprofile.yaml"
  "$USER_HOME/.zshrc"
  "$USER_HOME/.config/ghostty/config"
  "$USER_HOME/.zen/tizo6sbm.Default (release)/chrome/userChrome.css"
  "$USER_HOME/.zen/tizo6sbm.Default (release)/chrome/userContent.css"
  "$USER_HOME/.zen/tizo6sbm.Default (release)/chrome/natsumi-config.css"
)

DEST_FOLDER="$USER_HOME/Dev/Linux/Config"

echo -e "${BLUE}Creating $DEST_FOLDER if it doesn't exist"
mkdir -pv "$DEST_FOLDER"
chown "$SUDO_USER":"$SUDO_USER" "$DEST_FOLDER"

# Backing up configs
echo -e "\n${BLUE}Backing up configs to $DEST_FOLDER${RED}\n"

for i in "${CONFIGS[@]}"; do
  FILE_NAME=$(basename "$i")
  if [[ $(dirname "$i") == "$USER_HOME" ]]; then
    FILE_DIR="user"
  else
    FILE_DIR=$(basename "$(dirname "$i")")
  fi

  # This check is to make dot files (hidden files) visible
  if [[ $FILE_NAME == .* ]]; then
    FILE_NAME="${FILE_NAME#?}"
    # echo "$FILE_NAME"
  fi

  # This check is to make dot folders (hidden folders) visible
  if [[ $FILE_DIR == .* ]]; then
    FILE_DIR="${FILE_DIR#?}"
    # echo "$FILE_NAME"
  fi

  printf "${NC}"
  mkdir -pv "$DEST_FOLDER"/"$FILE_DIR"
  chown "$SUDO_USER":"$SUDO_USER" "$DEST_FOLDER"/"$FILE_DIR"
  printf "${RED}"
  cp "$i" "$DEST_FOLDER"/"$FILE_DIR"/"$FILE_NAME"
done

echo -e "\n${GREEN}Finished backing up configs${NC}"
