#!/usr/bin/env bash
# Not recommended to run without understanding what you're doing

# NetworkManager-wait-online.service was taking +8 sec which resulted in boot times of 33-40 sec
# Disabling it resulted in boot times of 20-25 sec
systemctl disable NetworkManager-wait-online.service
