#!/usr/bin/env bash

RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

# Check if it is a directory, file or invalid
isDir() {
	if [[ -d $1 ]]; then
		# This is a directory
		return 1
	elif [[ -f $1 ]]; then
		# This is a file
		return 2
	else
		# This is invalid
		return 0
	fi
}

# Handles logic according to the file type
handleType() {
	# If it is a directory, then go through the directory to check for files
	# or directories
	if [ "$1" -eq 1 ]; then
		for file in "$4"/*; do
			isDir "$file"
			TYPE=$?
			handleType "$TYPE" "$ROOT" "$ARTIST" "$file"
		done

	# If it is a file, check if it is an image
	elif [ "$1" -eq 2 ]; then
		MimeType=$(file "$4" --mime-type -b)

		# If it is an audio, print its information
		if [[ "$MimeType" == audio/* ]]; then
			AlbumTag=("$(ffprobe -v quiet -show_entries format_tags=album -of default=nw=1:nk=1 "$4")")
			ArtistTag=("$(ffprobe -v quiet -show_entries format_tags=album_artist -of default=nw=1:nk=1 "$4")")

			if [ "${AlbumTag[0]}" == '' ]; then
				AlbumTag=("$(ffprobe -v quiet -show_entries stream_tags=album -of default=nw=1:nk=1 "$4")")
				ArtistTag=("$(ffprobe -v quiet -show_entries stream_tags=album_artist -of default=nw=1:nk=1 "$4")")
			fi

			if [ "${ArtistTag[0]}" == '' ]; then
				ArtistTag=("$(ffprobe -v quiet -show_entries format_tags=artist -of default=nw=1:nk=1 "$4")")
				if [ "${ArtistTag[0]}" == '' ]; then
					ArtistTag=("$(ffprobe -v quiet -show_entries stream_tags=artist -of default=nw=1:nk=1 "$4")")
				fi
			fi

			PARENT="$(basename "$(dirname "$4")")"

			if [ "$ARTIST" = true ] && [ "$(basename "$(dirname "$PARENT")")" != "${ArtistTag[0]}" ]; then
				if [ "$ROOT" = true ]; then
					FOLDER="$DEST"/"${ArtistTag[0]}"/"${AlbumTag[0]}"
				else
					FOLDER="$(dirname "$4")"/"${ArtistTag[0]}"/"${AlbumTag[0]}"
				fi
				mkdir -pv "$FOLDER"
				chown "$SUDO_USER":"$SUDO_USER" "$FOLDER"
				mv "$4" "$FOLDER" >/dev/null 2>&1
			elif [ "$PARENT" != "${AlbumTag[0]}" ]; then
				if [ "$ROOT" = true ] && [ "$ARTIST" = true ]; then
					FOLDER="$DEST"/"${ArtistTag[0]}"/"${AlbumTag[0]}"
				elif [ "$ROOT" = true ]; then
					FOLDER="$DEST"/"${AlbumTag[0]}"
				elif [ "$ARTIST" = true ]; then
					FOLDER="$(dirname "$4")"/"${ArtistTag[0]}"/"${AlbumTag[0]}"
				else
					FOLDER="$(dirname "$4")"/"${AlbumTag[0]}"
				fi
				mkdir -pv "$FOLDER"
				chown "$SUDO_USER":"$SUDO_USER" "$FOLDER"
				mv "$4" "$FOLDER" >/dev/null 2>&1
			fi
		fi
	fi
}

if [ "$1" == '' ]; then
	DEST=$(pwd)
else
	DEST=$1
fi

echo -e "${BLUE}"
read -n 1 -rp "Sort files to root path? (Default is sorting to the file's current folder) [Y/n] " prompt

# Convert input to lowercase
prompt=${prompt,,}

#Add extra \n if not empty due to "enter" inserting a newline
if [[ -n "$prompt" ]]; then
	printf "\n"
fi

if [ "$prompt" == y ] || [ -z "$prompt" ]; then
	ROOT=true
fi

echo -e "${BLUE}"
read -n 1 -rp "Sort files into artist folders as well? (Default is only into album folders) [Y/n] " prompt

# Convert input to lowercase
prompt=${prompt,,}

#Add extra \n if not empty due to "enter" inserting a newline
if [[ -n "$prompt" ]]; then
	printf "\n"
fi

if [ "$prompt" == y ] || [ -z "$prompt" ]; then
	ARTIST=true
fi

isDir "$DEST"
TYPE=$?
echo -e "\n${BLUE}"Sorting through "$DEST"..."${NC}\n"
handleType "$TYPE" "$ROOT" "$ARTIST" "$DEST"
echo -e "\n${GREEN}"Sorting finished."${NC}"
